[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
headless = true
baseUrlPath = ""
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false